site_name: TimeGAN-Static
repo_url: https://github.com/Derkula/TimeGAN-Static
site_url: https://Derkula.github.io/TimeGAN-Static
site_description: https://github
site_author: Derkula
edit_uri: edit/main/docs/
repo_name: Derkula/TimeGAN-Static
copyright: Maintained by <a href="https://Derkula.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Derkula/TimeGAN-Static
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/TimeGAN-Static

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
